#!/usr/bin/env bash
# Work out which club-3090 backend should own :80, build a Caddyfile for it,
# and push that config to Caddy's admin API.
#
# Idempotent and cheap: if the generated config is byte-identical to the one
# already applied, nothing is sent. Safe to call on every docker event.
set -uo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib-discover.sh
source "${ROOT}/scripts/lib-discover.sh"

ALIAS="club3090"
ADMIN="127.0.0.1:2019"
STATE="${ROOT}/state"
PINNED="${STATE}/pinned"
PREFERRED="${STATE}/preferred"
APPLIED="${STATE}/Caddyfile.applied"
RETRY_LOCK="${STATE}/.retry.lock"

mkdir -p "$STATE"

log() { echo "[reconcile] $*" >&2; }

# --- the optional API key ----------------------------------------------------
PROXY_KEY=""
if [[ -f "${ROOT}/.env" ]]; then
	# Only PROXY_KEY is read; the file is not sourced, so a stray line in it
	# can never execute.
	PROXY_KEY=$(sed -n 's/^[[:space:]]*PROXY_KEY[[:space:]]*=[[:space:]]*//p' "${ROOT}/.env" | tail -1)
	PROXY_KEY="${PROXY_KEY%\"}"; PROXY_KEY="${PROXY_KEY#\"}"
	PROXY_KEY="${PROXY_KEY%\'}"; PROXY_KEY="${PROXY_KEY#\'}"
fi

# --- discovery ---------------------------------------------------------------
mapfile -t ROWS < <(discover)

PREF=$(read_state "$PREFERRED")
PIN=$(read_state "$PINNED")

ACTIVE_NAME=""; ACTIVE_PORT=""; ACTIVE_MODEL=""; VIA=""
AMBIGUOUS=0

# The standing preference wins whenever its engine is up, then the last
# explicit pick, then a lone backend. See select_active in lib-discover.sh.
SEL=$(printf '%s\n' "${ROWS[@]:-}" | select_active "$PREF" "$PIN")
if [[ -n "$SEL" ]]; then
	IFS=$'\t' read -r VIA ACTIVE_NAME ACTIVE_PORT ACTIVE_MODEL _ <<<"$SEL"
	# Only the self-election is recorded; a preference must not become a pin, or
	# it would keep deciding after the user cleared it.
	[[ "$VIA" == sole ]] && printf '%s\n' "$ACTIVE_NAME" >"$PINNED"
elif [[ ${#ROWS[@]} -gt 1 ]]; then
	# Several backends up and nothing selects one: refuse to guess. /b/<key>/
	# routes stay live so nothing is unreachable, but :80 asks for a decision.
	AMBIGUOUS=1
fi

# --- config signature --------------------------------------------------------
# A fingerprint of everything that shapes the config. It is embedded in the
# /_status body, which means it also shows up in Caddy's live JSON config —
# so "is the running Caddy already serving this config?" becomes a grep.
# That is what makes a bare `docker restart c3proxy-caddy` self-heal: the
# restarted Caddy is back on the bootstrap config, the signature is missing,
# and the next reconcile pushes for real instead of trusting a local cache.
sig_input="key=${PROXY_KEY}|active=${ACTIVE_NAME}:${ACTIVE_PORT}:${ACTIVE_MODEL}|via=${VIA}|pref=${PREF}|amb=${AMBIGUOUS}"
for row in "${ROWS[@]:-}"; do sig_input+="|cand=${row}"; done
SIG=$(printf '%s' "$sig_input" | sha256sum | cut -c1-16)

# --- JSON helpers ------------------------------------------------------------
jstr() { # minimal JSON string escaping
	local s="$1"
	s="${s//\\/\\\\}"; s="${s//\"/\\\"}"
	printf '"%s"' "$s"
}

status_json() {
	local first=1 out
	out='{"alias":'$(jstr "$ALIAS")
	out+=',"config_id":'$(jstr "$SIG")
	out+=',"key_required":'
	if [[ -n "$PROXY_KEY" ]]; then out+='true'; else out+='false'; fi
	out+=',"ambiguous":'
	if [[ $AMBIGUOUS -eq 1 ]]; then out+='true'; else out+='false'; fi
	out+=',"preferred":'
	if [[ -n "$PREF" ]]; then out+=$(jstr "$PREF"); else out+='null'; fi
	out+=',"selected_by":'
	if [[ -n "$VIA" ]]; then out+=$(jstr "$VIA"); else out+='null'; fi
	if [[ -n "$ACTIVE_NAME" ]]; then
		out+=',"active":{"container":'$(jstr "$ACTIVE_NAME")',"port":'"$ACTIVE_PORT"',"model":'$(jstr "$ACTIVE_MODEL")'}'
	else
		out+=',"active":null'
	fi
	out+=',"candidates":['
	for row in "${ROWS[@]:-}"; do
		[[ -z "$row" ]] && continue
		IFS=$'\t' read -r n p m u <<<"$row"
		[[ $first -eq 0 ]] && out+=','
		first=0
		out+='{"container":'$(jstr "$n")',"port":'"$p"',"model":'$(jstr "$m")',"uptime":'$(jstr "$u")',"path":'$(jstr "/b/${p}/")'}'
	done
	out+=']}'
	printf '%s' "$out"
}

# --- Caddyfile generation ----------------------------------------------------
# handle blocks are mutually exclusive and evaluated in written order, so the
# auth gate simply goes first.
gen_caddyfile() {
	cat <<-EOF
	# GENERATED by scripts/reconcile.sh — do not edit; edits are overwritten.
	{
		admin ${ADMIN}
		auto_https off
		order model_alias before reverse_proxy
		log {
			output stderr
			level ERROR
		}
	}

	:80 {
	EOF

	if [[ -n "$PROXY_KEY" ]]; then
		cat <<-EOF
			@unauth {
				not header Authorization "Bearer ${PROXY_KEY}"
				not header X-Api-Key "${PROXY_KEY}"
			}
			handle @unauth {
				header Content-Type application/json
				respond \`{"error":{"message":"unauthorized: send Authorization: Bearer <key> or x-api-key: <key>","type":"invalid_request_error","code":401}}\` 401
			}

		EOF
	fi

	cat <<-EOF
		handle /_status {
			header Content-Type application/json
			respond \`$(status_json)\` 200
		}

	EOF

	# One route per backend, keyed by both container name and port.
	for row in "${ROWS[@]:-}"; do
		[[ -z "$row" ]] && continue
		IFS=$'\t' read -r n p m _ <<<"$row"
		for key in "$n" "$p"; do
			cat <<-EOF
				handle_path /b/${key}/* {
					model_alias {
						alias ${ALIAS}
						target "${m}"
						expose_alias
					}
					reverse_proxy 127.0.0.1:${p}
				}

			EOF
		done
	done

	# Catch-all: the active backend, or an explanatory 503.
	if [[ -n "$ACTIVE_NAME" ]]; then
		cat <<-EOF
			handle {
				model_alias {
					alias ${ALIAS}
					target "${ACTIVE_MODEL}"
					expose_alias
				}
				reverse_proxy 127.0.0.1:${ACTIVE_PORT}
			}
		}
		EOF
	elif [[ $AMBIGUOUS -eq 1 ]]; then
		local list=""
		for row in "${ROWS[@]}"; do
			IFS=$'\t' read -r n p m _ <<<"$row"
			list+="${n} (:${p}, ${m}); "
		done
		cat <<-EOF
			handle {
				header Content-Type application/json
				respond \`{"error":{"message":"several club-3090 backends are running and none is preferred or pinned — run 'llmroute' to choose one, or 'llmroute prefer <name>' to make it stick. Candidates: ${list%; }","type":"service_unavailable","code":503}}\` 503
			}
		}
		EOF
	else
		cat <<-EOF
			handle {
				header Content-Type application/json
				respond \`{"error":{"message":"no club-3090 backend is running","type":"service_unavailable","code":503}}\` 503
			}
		}
		EOF
	fi
}

# --- apply -------------------------------------------------------------------
NEW=$(gen_caddyfile)

# C3_PRINT=1 dumps the config that would be applied and exits — used by the
# test suite and handy when debugging a route.
if [[ "${C3_PRINT:-0}" == "1" ]]; then
	printf '%s\n' "$NEW"
	exit 0
fi

if curl -s --max-time 5 "http://${ADMIN}/config/" 2>/dev/null | grep -q "$SIG"; then
	log "config unchanged"
	printf '%s' "$NEW" >"$APPLIED"
else
	if printf '%s' "$NEW" | curl -sS -X POST "http://${ADMIN}/load" \
		-H 'Content-Type: text/caddyfile' --data-binary @- >/dev/null; then
		printf '%s' "$NEW" >"$APPLIED"
		if [[ -n "$ACTIVE_NAME" ]]; then
			log ":80 => :${ACTIVE_PORT} ${ACTIVE_NAME} (${ACTIVE_MODEL}) [${VIA}]"
		elif [[ $AMBIGUOUS -eq 1 ]]; then
			log "${#ROWS[@]} backends running, none preferred or pinned — run llmroute"
		else
			log "no backend running"
		fi
	else
		log "admin API refused the config (is the caddy container up?)"
		exit 1
	fi
fi

# A backend that is still loading reports a fallback model name. Come back
# once for the real one. mkdir is the lock: only one retry can be in flight.
if [[ -n "$ACTIVE_PORT" ]] && ! endpoint_ready "$ACTIVE_PORT"; then
	if mkdir "$RETRY_LOCK" 2>/dev/null; then
		log "backend still booting; re-checking in 15s"
		( sleep 15; rmdir "$RETRY_LOCK" 2>/dev/null; "$0" >/dev/null 2>&1 ) &
		disown 2>/dev/null || true
	fi
fi
